# Generated by Django 5.0.14 on 2025-06-26 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage_form', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('quantity_in', models.PositiveIntegerField(default=0)),
                ('quantity_out', models.PositiveIntegerField(default=0)),
                ('prescribing_doctor', models.CharField(blank=True, max_length=100)),
                ('dispensed_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
