# Generated by Django 5.0.14 on 2025-06-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicineinventory',
            old_name='dispensed_by',
            new_name='dispensed_to',
        ),
        migrations.RenameField(
            model_name='medicineinventory',
            old_name='prescribing_doctor',
            new_name='storage_condition',
        ),
    ]
