# Generated by Django 5.0.14 on 2025-06-29 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_dispensed_by_medicineinventory_dispensed_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=50)),
                ('dispensed_to', models.CharField(max_length=100)),
                ('quantity_out', models.PositiveIntegerField()),
            ],
        ),
    ]
