# Generated by Django 5.2.7 on 2025-10-20 11:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_dispensehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('near_expiry', 'Near Expiry'), ('expired', 'Expired')], max_length=20)),
                ('message', models.TextField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='dispensehistory',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='medicineinventory',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='dispensehistory',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_medicines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispensehistory',
            name='inventory_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispense_records', to='inventory.medicineinventory'),
        ),
        migrations.AddField(
            model_name='dispensehistory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dispensehistory',
            name='patient_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dispensehistory',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dispensehistory',
            name='prescribing_doctor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dispensehistory',
            name='prescription_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='generic_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='prescribing_doctor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g., 500mg, 10ml', max_length=50),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='batch_no',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='medicine_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='storage_condition',
            field=models.CharField(blank=True, choices=[('room_temp', 'Room Temperature'), ('refrigerated', 'Refrigerated (2-8°C)'), ('frozen', 'Frozen (-20°C)'), ('controlled_temp', 'Controlled Temperature')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='medicineinventory',
            index=models.Index(fields=['medicine_name'], name='inventory_m_medicin_999a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineinventory',
            index=models.Index(fields=['batch_no'], name='inventory_m_batch_n_e556bc_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineinventory',
            index=models.Index(fields=['expiry_date'], name='inventory_m_expiry__b9c56e_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineinventory',
            index=models.Index(fields=['date'], name='inventory_m_date_23d024_idx'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
